apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmaite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmaite.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.nebariapp.service.port | default 5006 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "checkmaite.selectorLabels" . | nindent 4 }}
